spring:
  profiles:
    active: local
app:
  headers:
    auth-token-header: Authorization
  user:
    default-profile-image-url: "https://bit.ly/4eeCLvy"
oauth2:
  clients:
    kakao:
      resource-uri: https://kapi.kakao.com/v2/user/me