spring:
  jpa:
    open-in-view: false
  data:
    redis:
      repositories:
        enabled: false
  profiles:
    active: local
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
app:
  max-friends-count: 20
  music-search-limit: 10
  headers:
    auth-token-header: Authorization
  user:
    default-profile-image-url: "https://bit.ly/4eeCLvy"
oauth2:
  clients:
    kakao:
      resource-uri: https://kapi.kakao.com/v2/user/me